//
//  MovieDetailModels.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail
{
    // MARK: Use cases
    enum BarButtonImage: String {
        case favorite = "stared"
        case notFavorite = "star"
        
        var image: String {
            return self.rawValue
        }
    }
    struct Request: BaseRequest {
        var requestURL: String
    }
    
    struct Response: Codable {
        let adult : Bool?
        let backdrop_path : String?
        let belongs_to_collection : BelongsToCollection?
        let budget : Int?
        let genres : [Genres]?
        let homepage : String?
        let id : Int?
        let imdb_id : String?
        let original_language : String?
        let original_title : String?
        let overview : String?
        let popularity : Double?
        let poster_path : String?
        let production_companies : [ProductionCompanies]?
        let production_countries : [ProductionCountries]?
        let release_date : String?
        let revenue : Int?
        let runtime : Int?
        let spoken_languages : [SpokenLanguages]?
        let status : String?
        let tagline : String?
        let title : String?
        let video : Bool?
        let vote_average : Double?
        let vote_count : Int?
    }
    
    struct Genres : Codable {
        let id : Int?
        let name : String?
    }
    
    struct BelongsToCollection : Codable {
        let id : Int?
        let name : String?
        let poster_path : String?
        let backdrop_path : String?
    }

    struct ProductionCompanies : Codable {
        let id : Int?
        let logo_path : String?
        let name : String?
        let origin_country : String?
    }
    
    struct ProductionCountries : Codable {
        let iso_3166_1 : String?
        let name : String?
    }
    
    struct SpokenLanguages : Codable {
        let english_name : String?
        let iso_639_1 : String?
        let name : String?
    }
    
    struct ViewModel{
        let backDropPath : String?
        let title: String?
        let overView: String?
        let voteCount: String?
        
        init(backDropPath: String?, title: String?, overView: String?, voteCount: String?) {
            self.backDropPath = "https://image.tmdb.org/t/p/w400" + (backDropPath ?? "")
            self.title = title
            self.overView = overView
            self.voteCount = voteCount
        }
    }
}
