//
//  MoviewDetailRouter.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MovieDetailRoutingLogic {
    func routeToBack()
}

protocol MovieDetailDataPassing {
    var dataStore: MovieDetailDataStore? { get }
}

final class MovieDetailRouter: NSObject, MovieDetailRoutingLogic, MovieDetailDataPassing {
    weak var viewController: MovieDetailViewController?
    var dataStore: MovieDetailDataStore?
    
    func routeToBack() {
        passDataToPreviousViewController()
        navigateToBack()
    }
    
    func passDataToPreviousViewController() {
        if let destinationVC = previousViewController(), let sourceDataStore = dataStore {
            
            var destinationDS = destinationVC.router?.dataStore!
            destinationDS?.selectedMovie = sourceDataStore.selectedMovie
            destinationVC.reloadData()
        }
    }
    
    func navigateToBack() {
        viewController?.navigationController?.popViewController(animated: true)
    }
    
    func previousViewController() -> MovieListViewController? {
        
        if let viewControllers = viewController?.navigationController?.viewControllers, viewControllers.count > 1 {
            return viewControllers[viewControllers.count - 2] as? MovieListViewController
        }
        return nil
    }
}
