//
//  MovieDetailPresenterTests.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 5.02.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheMovieApp
import XCTest

final class MovieDetailPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MovieDetailPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupMovieDetailPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMovieDetailPresenter() {
        sut = MovieDetailPresenter()
    }
    
    // MARK: Test doubles
    
    class MovieDetailDisplayLogicSpy: MovieDetailDisplayLogic {
        
        var displayDetailCalled = false
        var displayFavoriteButtonCalled = false
        
        func displayDetail(viewModel: MovieDetail.ViewModel) {
            displayDetailCalled = true
        }
        
        func displayFavoriteButton(isFavorite: Bool) {
            displayFavoriteButtonCalled = true
        }
    
    }
    
    // MARK: Tests
    
    func testPresentDetail() {
        // Given
        let spy = MovieDetailDisplayLogicSpy()
        sut.viewController = spy
        let response = MovieDetail.Response(adult: nil,
                                            backdrop_path: nil,
                                            belongs_to_collection: nil,
                                            budget: nil,
                                            genres: nil,
                                            homepage: nil,
                                            id: nil,
                                            imdb_id: nil,
                                            original_language: nil,
                                            original_title: nil,
                                            overview: nil,
                                            popularity: nil,
                                            poster_path: nil,
                                            production_companies: nil,
                                            production_countries: nil,
                                            release_date: nil,
                                            revenue: nil,
                                            runtime: nil,
                                            spoken_languages: nil,
                                            status: nil,
                                            tagline: nil,
                                            title: nil,
                                            video: nil,
                                            vote_average: nil,
                                            vote_count: nil)
        
        // When
        sut.presentDetail(response: response)
        
        // Then
        XCTAssertTrue(spy.displayDetailCalled)
    }
    
    func testPresentFavoriteButton() {
        // Given
        let spy = MovieDetailDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.presentFavoriteButton(isFavorite: true)
        
        // Then
        XCTAssertTrue(spy.displayFavoriteButtonCalled)
    }
    
}
