//
//  MovieListModels.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieList {
    
    // MARK: Use cases
    
    enum PopularMovies {
        
        struct Request: BaseRequest {
            var requestURL: String
        }
        
        struct Response : Codable {
            let page : Int?
            let results : [Results]?
            let total_pages : Int?
            let total_results : Int?
        }
        
        struct Results : Codable {
            let adult : Bool?
            let backdrop_path : String?
            let genre_ids : [Int]?
            let id : Int?
            let original_language : String?
            let original_title : String?
            let overview : String?
            let popularity : Double?
            let poster_path : String?
            let release_date : String?
            let title : String?
            let video : Bool?
            let vote_average : Double?
            let vote_count : Int?
        }
        
        struct ViewModel {
            let page : Int?
            let results : [Results]?
            let total_pages : Int?
        }
    }
}
