//
//  MovieListPresenterTests.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 4.02.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheMovieApp
import XCTest

final class MovieListPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: MovieListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupMovieListPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupMovieListPresenter() {
        sut = MovieListPresenter()
    }
    
    // MARK: Test doubles
    
    class MovieListDisplayLogicSpy: MovieListDisplayLogic {
        
        var displayMoviesCalled: Bool = false
        var displayDetailCalled: Bool = false
        
        func displayMovies(viewModel: MovieList.PopularMovies.ViewModel) {
            displayMoviesCalled = true
        }
        
        func displayDetail() {
            displayDetailCalled = true
        }
        
    }
    
    // MARK: Tests
    
    func testPresentMovies() {
        // Given
        let spy = MovieListDisplayLogicSpy()
        sut.viewController = spy
        let response =  MovieList.PopularMovies.Response(page: 0, results: nil, total_pages: 1, total_results: 1)
        
        // When
        sut.presentMovies(response: response)
        
        // Then
        XCTAssertTrue(spy.displayMoviesCalled, "presentMovies(response:) should ask the view controller to display the result")
    }
    
    func testPresentDetail() {
        // Given
        let spy = MovieListDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        sut.presentDetail()
        
        // Then
        XCTAssertTrue(spy.displayDetailCalled, "presentDetail() should ask the view controller to display the result")
    }
}
