//
//  MoviewDetailViewController.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailDisplayLogic: class{
    func displayDetail(viewModel: MovieDetail.ViewModel)
    func displayFavoriteButton(isFavorite: Bool)
}

final class MovieDetailViewController: UIViewController, MovieDetailDisplayLogic {
    
    @IBOutlet weak var tableView: UITableView!
    
    var interactor: MovieDetailBusinessLogic?
    var router: (NSObjectProtocol & MovieDetailRoutingLogic & MovieDetailDataPassing)?
    var viewModel: MovieDetail.ViewModel!
    let barButton = BarButton()
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MovieDetailInteractor()
        let presenter = MovieDetailPresenter()
        let router = MovieDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        tableView.rowHeight = UITableView.automaticDimension
        initBarButton()
        customBackButton()
        interactor?.getDetail()
        interactor?.changeFavoriteStatus()        
    }
    
    // MARK: UI
    
    func customBackButton() {
        navigationItem.hidesBackButton = true
        let image = UIImage(named: "backIcon")
        let button = UIBarButtonItem(image: image, style: .plain, target: self, action: #selector(backButtonAction))
        navigationItem.leftBarButtonItem = button
    }
    
    func initBarButton() {
        barButton.addTarget(self, action: #selector(tappedFavorite), for: .touchUpInside)
        self.navigationItem.rightBarButtonItem = barButton.barButtonItem
    }
    
    @objc func backButtonAction() {
        router?.routeToBack()
    }
    
    @objc func tappedFavorite() {
        interactor?.favoriteStatus()
    }

    // MARK: Display
    
    func displayDetail(viewModel: MovieDetail.ViewModel) {
        self.viewModel = viewModel
        DispatchQueue.main.async {
            self.tableView.reloadData()
        }
    }
    
    func displayFavoriteButton(isFavorite: Bool) {
        var image: UIImage?
        
        if isFavorite {
            image = UIImage(named: MovieDetail.BarButtonImage.favorite.image)
        } else {
            image = UIImage(named: MovieDetail.BarButtonImage.notFavorite.image)
        }
        barButton.setImage(image, for: .normal)
    }
}
