//
//  MoviewDetailViewController.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviewDetailDisplayLogic: class{
    func displayDetail(viewModel: MoviewDetail.ViewModel)
}

final class MoviewDetailViewController: UIViewController, MoviewDetailDisplayLogic {
    
    var interactor: MoviewDetailBusinessLogic?
    var router: (NSObjectProtocol & MoviewDetailRoutingLogic & MoviewDetailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = MoviewDetailInteractor()
        let presenter = MoviewDetailPresenter()
        let router = MoviewDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = MoviewDetail.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displayDetail(viewModel: MoviewDetail.ViewModel) {
        <#code#>
    }
}
