//
//  MoviewDetailInteractor.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MoviewDetailBusinessLogic {
    func getDetail()
}

protocol MoviewDetailDataStore {
    var movieID: String? { get set }
}

final class MoviewDetailInteractor: MoviewDetailBusinessLogic, MoviewDetailDataStore {
    var presenter: MoviewDetailPresentationLogic?
    var worker: MoviewDetailWorker?
    var movieID: String?
    
    func getDetail() {
        let request = MoviewDetail.Request(requestURL: RequestURL.MovieList.popularMovies.url + page)

        ServiceAPI.shared.callService(request: request, response: MoviewDetail.Response) { (result) in
            
            switch result {
            case .success(let response):
                self.presenter?.presentPopularMovies(response: response)
                print(response)
                print("totalPages:",response.total_pages ?? "nil")
            case .failure(let error):
                print("the error \(error)")
            }
        }
        
    }
}
