//
//  MoviewDetailInteractor.swift
//  TheMovieApp
//
//  Created by CİHAN ÖZTÜRK on 29.01.2021.
//  Copyright (c) 2021 CİHAN ÖZTÜRK. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailBusinessLogic {
    func getDetail()
}

protocol MovieDetailDataStore {
    var movieID: String? { get set }
}

final class MovieDetailInteractor: MovieDetailBusinessLogic, MovieDetailDataStore {
    var presenter: MovieDetailPresentationLogic?
    var movieID: String?
    
    func getDetail() {
        let request = MovieDetail.Request(requestURL:
            RequestURL.MovieDetail.detail.url.replacingOccurrences(of: "#",
                                                                   with: movieID ?? ""))

        ServiceAPI.shared.callService(request: request, response: MovieDetail.Response.self) { (result) in
            
            switch result {
            case .success(let response):
                self.presenter?.presentDetail(response: response)
                print(response)
            case .failure(let error):
                print("the error \(error)")
            }
        }
        
    }
}
